### ISSUE TITLE
Create a Rekor verifier: tlog and rekor properties

### ISSUE THREAD

**Issue by asraa** [sigstore/sigstore-go-archived#11]
**Description**

The Rekor verifier has two parts:
1. Verify the tlog properties: inclusion, consistency, root hash
2. Verify that a Rekor entry matches [Input](https://github.com/sigstore/protobuf-specs/blob/ad5ffe19995d693817607c041b16d93745a6fd4d/protos/sigstore_verification.proto#L132-L135) by matching canonicalized input entries against the Rekor entry.

The API surface can look something like this: https://github.com/sigstore/rekor/blob/main/pkg/verify/verify.go? but the sharding logic needs to be independent.

**Comment by asraa** [comment]
@cdris

**Comment by Hayden-IO** [comment]
We should prioritize offline verification with an inclusion proof + checkpoint, and also verify the SET (which has been added). We should also support online verification, but as a lower priority.
