### ISSUE TITLE
Design top-level verification function

### ISSUE THREAD

**Issue by asraa** [sigstore/sigstore-go-archived#18]
**Description**

I'd like to get a rough sketch of the top-level verification done so it's easier to hcunk out the rest of the work

This doc describes the basic steps for bundle verification: 
https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#

The top-level should look something like

`VerifyBundle(bundle bundle_v1.Bundle, root trustroot_v1.TrustedRoot, options v1_verification.ArtifactVerificationOptions)`

**Comment by Hayden-IO** [comment]
Once the changes that are currently ongoing in Cosign are in for verification, do we want to start with that as a template and refactor from there?

**Comment by asraa** [comment]
I'd like to go off of the spec since that aligns with the protobuf spec inputs, but the steps are almost the same anyway now :)

**Comment by asraa** [comment]
As in: the Cosign code doesn't iterate through multiple transparency log entries in the bundle, which is what this design would need to do.

**Comment by lumjjb** [comment]
requested access to the doc!

**Comment by znewman01** [comment]
I believe that doc should be visible to anyone in the [sigstore-dev@googlegroups.com](https://groups.google.com/g/sigstore-dev) group

**Comment by lumjjb** [comment]
Thanks!
