### ISSUE TITLE
Repository layout and implementation start

### ISSUE THREAD

**Issue by asraa** [sigstore/sigstore-go-archived#3]
**Description**

I wanted to start this issue to start discussion project content, layout, and what we can get started working on ASAP and what's gated on some of the protobuf specifications.

Here's a list of the content I think we need to include, please add, modify, inline. I don't mind:

Utilities that are not gated by the work in sigstore/protobuf-specs:
3. LIGHTWEIGHT Rekor clients and verifiers
4. LIGHTWEIGHT Fulcio clients and verifiers
5. LIGHTWEIGHT CTFE clients and verifiers
6. LIGHTWEIGHT TSA clients and verifiers (TBD)
7. Trust root clients

Some of this work is TBD on the formats for trust root client outputs (https://github.com/sigstore/protobuf-specs/issues/4) and ideally the lightweight clients also use the protobufs defined here (https://github.com/sigstore/protobuf-specs/tree/main/protos)

It may be easier to start with the rekor client and verification modeled after https://github.com/sigstore/protobuf-specs/blob/main/protos/sigstore_rekor.proto. 

Writing top-level signing and verification commands should be easier once we have all these pieces first.
WDYT?

**Comment by asraa** [comment]
cc @haydentherapper @cdris for Rekor verification

**Comment by Hayden-IO** [comment]
How do we plan to give maintainers in the respective repos ownership over the clients and verifiers? Do we want the clients in sigstore-go, or to keep them in their respective repos? I think verification logic makes sense since that needs to be shared across Sigstore repos, but I'm not sure about clients.

**Comment by asraa** [comment]
> Do we want the clients in sigstore-go, or to keep them in their respective repos? 

I think it's only the question of Rekor -- Fulcio's client isn't heavyweight and perform verification. 
It would be good to have labels here and have a maintainer from those repos sign-off.

>  I think verification logic makes sense since that needs to be shared across Sigstore repos, but I'm not sure about clients.

Ah, ok sorry, clarifying: verification clients, we can obviously import the generated rekor clients, but I don't want to pull in any  Rekor CLI code.
