### ISSUE TITLE
ensure FIPs compliance

### ISSUE THREAD

**Issue by lukehinds** [sigstore/sigstore-go-archived#30]
We should really try to address this from the start this time in sigstore-go. As it stands sigstore cannot be used on public sector sites and likely in verticals such as banking, telco etc, due to us being non FIPs compliant

https://github.com/sigstore/cosign/issues/94

**Comment by sunstonesecure-robert** [comment]
can it use the OS fips crypto provider instead of rolling its own crypto? or a HSM HW device via PKCS#11?

**Comment by znewman01** [comment]
To clarify, Cosign has never implemented its own crypto.

Cosign uses the Go standard library crypto implementation. Compiling Go's crypto library against BoringSSL is possible (but considered experimental by Go). This may or may not result in a FIPS-compliant Cosign; you'd have to ask a lawyer.

It is currently possible to use PKCS#11 signing with Cosign as well.

See the Cosign issue: https://github.com/sigstore/cosign/issues/94
