### ISSUE TITLE
Complete the TUF client implementation

### ISSUE THREAD

**Issue by Hayden-IO** [sigstore/sigstore-go-archived#60]
**Description**

Started in https://github.com/sigstore/sigstore-go/pull/7

**Comment by Hayden-IO** [comment]
@asraa, do you think we could pull in the TUF client from sigstore/sigstore to start, or should we keep iterating on this new implementation?

**Comment by asraa** [comment]
I'd start new, at least to fix the issues before (like the timestamp expiry / cache refresh thing)
